version: "4.1.0"
services:
  database:
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      RAILS_ENV: development
      POSTGRES_PASSWORD: ENV['POSTGRES_PASSWORD']
      POSTGRES_DB: ENV['POSTGRES_DB']
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/smartflix
      - gem_cache:/usr/local/bundle/gems
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    env_file: .env.development
    environment:
      RAILS_ENV: development
      DATABASE_HOST: database
  redis:
    image: redis:6.2.1
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - database
      - redis
      - web
    volumes:
      - .:/smartflix
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
volumes:
  db_data:
  gem_cache:
