---
  :concurrency: 3
  :queues:
    - movies
    - default
  :schedule:
      update_movie_worker:
          cron: '00 07 * * *'
          class: UpdateMovieWorker
      destroy_movie_worker:
          cron: '00 08 * * *'
          class: DestroyMovieWorker
