---
  :concurrency: 3
  :queues:
    - movies
    - default
  :schedule:
      batch_update_movie_worker:
          cron: '00 07 * * *'
          class: BatchUpdateMovieWorker
      destroy_movie_worker:
          cron: '00 08 * * *'
          class: DestroyMovieWorker
